project:
  type: website

website:
  title: "Fieldnotes"
  sidebar:
    style: "docked"
    search: true
    contents:
      - section: "Basics: data export from the internet archive"
        contents:
          - text: "Data basis: sampling and structure"
            file: sites/datengrundlage.qmd
          - text: "Data cleaning"
            file: sites/data-cleaning.qmd
          - text: "Data cleaning - second export"
            file: sites/data-cleaning-2.qmd
          - text: "Matching scripts files to html pages"
            file: sites/script-files-to-html-pages.qmd
      - section: "Parsing: How to find commenting possibilities in HTML?"
        contents:
          - text: "Different approaches how to interpret HTML"
            file: sites/approaches.qmd
          - text: "Learning about infrastructure: Analyzing doctype"
            file: sites/analyzing-doctypes.qmd
          - text: "Analyzing form tags"
            file: sites/analyzing-form-tags.qmd
          - text: "Context of form tags"
            file: sites/form-context.qmd
          - text: "Analyzing script tags"
            file: sites/analyzing-script-tags.qmd
          - text: "Analyzing iframes"
            file: sites/analyzing-iframes.qmd
          - text: "Analyzing specific snippets"
            file: sites/analyzing-all-tags.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true


